// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/rpc/node_rpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Val           string                 `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetResponse) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *PutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GossipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	HashSlotsStart uint32                 `protobuf:"varint,3,opt,name=hash_slots_start,json=hashSlotsStart,proto3" json:"hash_slots_start,omitempty"`
	HashSlotsEnd   uint32                 `protobuf:"varint,4,opt,name=hash_slots_end,json=hashSlotsEnd,proto3" json:"hash_slots_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *GossipRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GossipRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GossipRequest) GetHashSlotsStart() uint32 {
	if x != nil {
		return x.HashSlotsStart
	}
	return 0
}

func (x *GossipRequest) GetHashSlotsEnd() uint32 {
	if x != nil {
		return x.HashSlotsEnd
	}
	return 0
}

type NodeConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	HashSlotsStart uint32                 `protobuf:"varint,3,opt,name=hash_slots_start,json=hashSlotsStart,proto3" json:"hash_slots_start,omitempty"`
	HashSlotsEnd   uint32                 `protobuf:"varint,4,opt,name=hash_slots_end,json=hashSlotsEnd,proto3" json:"hash_slots_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *NodeConfig) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeConfig) GetHashSlotsStart() uint32 {
	if x != nil {
		return x.HashSlotsStart
	}
	return 0
}

func (x *NodeConfig) GetHashSlotsEnd() uint32 {
	if x != nil {
		return x.HashSlotsEnd
	}
	return 0
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	OtherNodes    []*NodeConfig          `protobuf:"bytes,2,rep,name=other_nodes,json=otherNodes,proto3" json:"other_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *GossipResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GossipResponse) GetOtherNodes() []*NodeConfig {
	if x != nil {
		return x.OtherNodes
	}
	return nil
}

type SetNodeConfigOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HashSlotsStart uint32                 `protobuf:"varint,1,opt,name=hash_slots_start,json=hashSlotsStart,proto3" json:"hash_slots_start,omitempty"`
	HashSlotsEnd   uint32                 `protobuf:"varint,2,opt,name=hash_slots_end,json=hashSlotsEnd,proto3" json:"hash_slots_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetNodeConfigOptions) Reset() {
	*x = SetNodeConfigOptions{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeConfigOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeConfigOptions) ProtoMessage() {}

func (x *SetNodeConfigOptions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeConfigOptions.ProtoReflect.Descriptor instead.
func (*SetNodeConfigOptions) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *SetNodeConfigOptions) GetHashSlotsStart() uint32 {
	if x != nil {
		return x.HashSlotsStart
	}
	return 0
}

func (x *SetNodeConfigOptions) GetHashSlotsEnd() uint32 {
	if x != nil {
		return x.HashSlotsEnd
	}
	return 0
}

type SetClusterConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThisNode      *SetNodeConfigOptions  `protobuf:"bytes,1,opt,name=this_node,json=thisNode,proto3" json:"this_node,omitempty"`
	OtherNodes    []*NodeConfig          `protobuf:"bytes,2,rep,name=other_nodes,json=otherNodes,proto3" json:"other_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClusterConfigRequest) Reset() {
	*x = SetClusterConfigRequest{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClusterConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClusterConfigRequest) ProtoMessage() {}

func (x *SetClusterConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClusterConfigRequest.ProtoReflect.Descriptor instead.
func (*SetClusterConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *SetClusterConfigRequest) GetThisNode() *SetNodeConfigOptions {
	if x != nil {
		return x.ThisNode
	}
	return nil
}

func (x *SetClusterConfigRequest) GetOtherNodes() []*NodeConfig {
	if x != nil {
		return x.OtherNodes
	}
	return nil
}

type SetClusterConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClusterConfigResponse) Reset() {
	*x = SetClusterConfigResponse{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClusterConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClusterConfigResponse) ProtoMessage() {}

func (x *SetClusterConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClusterConfigResponse.ProtoReflect.Descriptor instead.
func (*SetClusterConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *SetClusterConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetClusterConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterConfigRequest) Reset() {
	*x = GetClusterConfigRequest{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterConfigRequest) ProtoMessage() {}

func (x *GetClusterConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterConfigRequest.ProtoReflect.Descriptor instead.
func (*GetClusterConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{14}
}

type GetClusterConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ThisNode      *NodeConfig            `protobuf:"bytes,2,opt,name=this_node,json=thisNode,proto3" json:"this_node,omitempty"`
	OtherNodes    []*NodeConfig          `protobuf:"bytes,3,rep,name=other_nodes,json=otherNodes,proto3" json:"other_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterConfigResponse) Reset() {
	*x = GetClusterConfigResponse{}
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterConfigResponse) ProtoMessage() {}

func (x *GetClusterConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterConfigResponse.ProtoReflect.Descriptor instead.
func (*GetClusterConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *GetClusterConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetClusterConfigResponse) GetThisNode() *NodeConfig {
	if x != nil {
		return x.ThisNode
	}
	return nil
}

func (x *GetClusterConfigResponse) GetOtherNodes() []*NodeConfig {
	if x != nil {
		return x.OtherNodes
	}
	return nil
}

var File_internal_rpc_node_rpc_proto protoreflect.FileDescriptor

const file_internal_rpc_node_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/rpc/node_rpc.proto\x12\bnode_rpc\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"A\n" +
	"\vGetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x03 \x01(\tR\x03val\"0\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\"\x1d\n" +
	"\vPutResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x92\x01\n" +
	"\rGossipRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12(\n" +
	"\x10hash_slots_start\x18\x03 \x01(\rR\x0ehashSlotsStart\x12$\n" +
	"\x0ehash_slots_end\x18\x04 \x01(\rR\fhashSlotsEnd\"\x8f\x01\n" +
	"\n" +
	"NodeConfig\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12(\n" +
	"\x10hash_slots_start\x18\x03 \x01(\rR\x0ehashSlotsStart\x12$\n" +
	"\x0ehash_slots_end\x18\x04 \x01(\rR\fhashSlotsEnd\"W\n" +
	"\x0eGossipResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x125\n" +
	"\vother_nodes\x18\x02 \x03(\v2\x14.node_rpc.NodeConfigR\n" +
	"otherNodes\"f\n" +
	"\x14SetNodeConfigOptions\x12(\n" +
	"\x10hash_slots_start\x18\x01 \x01(\rR\x0ehashSlotsStart\x12$\n" +
	"\x0ehash_slots_end\x18\x02 \x01(\rR\fhashSlotsEnd\"\x8d\x01\n" +
	"\x17SetClusterConfigRequest\x12;\n" +
	"\tthis_node\x18\x01 \x01(\v2\x1e.node_rpc.SetNodeConfigOptionsR\bthisNode\x125\n" +
	"\vother_nodes\x18\x02 \x03(\v2\x14.node_rpc.NodeConfigR\n" +
	"otherNodes\"*\n" +
	"\x18SetClusterConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x19\n" +
	"\x17GetClusterConfigRequest\"\x94\x01\n" +
	"\x18GetClusterConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\tthis_node\x18\x02 \x01(\v2\x14.node_rpc.NodeConfigR\bthisNode\x125\n" +
	"\vother_nodes\x18\x03 \x03(\v2\x14.node_rpc.NodeConfigR\n" +
	"otherNodes2\xeb\x03\n" +
	"\fStoreService\x127\n" +
	"\x04Ping\x12\x15.node_rpc.PingRequest\x1a\x16.node_rpc.PingResponse\"\x00\x124\n" +
	"\x03Get\x12\x14.node_rpc.GetRequest\x1a\x15.node_rpc.GetResponse\"\x00\x124\n" +
	"\x03Put\x12\x14.node_rpc.PutRequest\x1a\x15.node_rpc.PutResponse\"\x00\x12=\n" +
	"\x06Delete\x12\x17.node_rpc.DeleteRequest\x1a\x18.node_rpc.DeleteResponse\"\x00\x12=\n" +
	"\x06Gossip\x12\x17.node_rpc.GossipRequest\x1a\x18.node_rpc.GossipResponse\"\x00\x12[\n" +
	"\x10SetClusterConfig\x12!.node_rpc.SetClusterConfigRequest\x1a\".node_rpc.SetClusterConfigResponse\"\x00\x12[\n" +
	"\x10GetClusterConfig\x12!.node_rpc.GetClusterConfigRequest\x1a\".node_rpc.GetClusterConfigResponse\"\x00B)Z'github.com/ethan-stone/go-key-store/rpcb\x06proto3"

var (
	file_internal_rpc_node_rpc_proto_rawDescOnce sync.Once
	file_internal_rpc_node_rpc_proto_rawDescData []byte
)

func file_internal_rpc_node_rpc_proto_rawDescGZIP() []byte {
	file_internal_rpc_node_rpc_proto_rawDescOnce.Do(func() {
		file_internal_rpc_node_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_node_rpc_proto_rawDesc), len(file_internal_rpc_node_rpc_proto_rawDesc)))
	})
	return file_internal_rpc_node_rpc_proto_rawDescData
}

var file_internal_rpc_node_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_rpc_node_rpc_proto_goTypes = []any{
	(*PingRequest)(nil),              // 0: node_rpc.PingRequest
	(*PingResponse)(nil),             // 1: node_rpc.PingResponse
	(*GetRequest)(nil),               // 2: node_rpc.GetRequest
	(*GetResponse)(nil),              // 3: node_rpc.GetResponse
	(*PutRequest)(nil),               // 4: node_rpc.PutRequest
	(*PutResponse)(nil),              // 5: node_rpc.PutResponse
	(*DeleteRequest)(nil),            // 6: node_rpc.DeleteRequest
	(*DeleteResponse)(nil),           // 7: node_rpc.DeleteResponse
	(*GossipRequest)(nil),            // 8: node_rpc.GossipRequest
	(*NodeConfig)(nil),               // 9: node_rpc.NodeConfig
	(*GossipResponse)(nil),           // 10: node_rpc.GossipResponse
	(*SetNodeConfigOptions)(nil),     // 11: node_rpc.SetNodeConfigOptions
	(*SetClusterConfigRequest)(nil),  // 12: node_rpc.SetClusterConfigRequest
	(*SetClusterConfigResponse)(nil), // 13: node_rpc.SetClusterConfigResponse
	(*GetClusterConfigRequest)(nil),  // 14: node_rpc.GetClusterConfigRequest
	(*GetClusterConfigResponse)(nil), // 15: node_rpc.GetClusterConfigResponse
}
var file_internal_rpc_node_rpc_proto_depIdxs = []int32{
	9,  // 0: node_rpc.GossipResponse.other_nodes:type_name -> node_rpc.NodeConfig
	11, // 1: node_rpc.SetClusterConfigRequest.this_node:type_name -> node_rpc.SetNodeConfigOptions
	9,  // 2: node_rpc.SetClusterConfigRequest.other_nodes:type_name -> node_rpc.NodeConfig
	9,  // 3: node_rpc.GetClusterConfigResponse.this_node:type_name -> node_rpc.NodeConfig
	9,  // 4: node_rpc.GetClusterConfigResponse.other_nodes:type_name -> node_rpc.NodeConfig
	0,  // 5: node_rpc.StoreService.Ping:input_type -> node_rpc.PingRequest
	2,  // 6: node_rpc.StoreService.Get:input_type -> node_rpc.GetRequest
	4,  // 7: node_rpc.StoreService.Put:input_type -> node_rpc.PutRequest
	6,  // 8: node_rpc.StoreService.Delete:input_type -> node_rpc.DeleteRequest
	8,  // 9: node_rpc.StoreService.Gossip:input_type -> node_rpc.GossipRequest
	12, // 10: node_rpc.StoreService.SetClusterConfig:input_type -> node_rpc.SetClusterConfigRequest
	14, // 11: node_rpc.StoreService.GetClusterConfig:input_type -> node_rpc.GetClusterConfigRequest
	1,  // 12: node_rpc.StoreService.Ping:output_type -> node_rpc.PingResponse
	3,  // 13: node_rpc.StoreService.Get:output_type -> node_rpc.GetResponse
	5,  // 14: node_rpc.StoreService.Put:output_type -> node_rpc.PutResponse
	7,  // 15: node_rpc.StoreService.Delete:output_type -> node_rpc.DeleteResponse
	10, // 16: node_rpc.StoreService.Gossip:output_type -> node_rpc.GossipResponse
	13, // 17: node_rpc.StoreService.SetClusterConfig:output_type -> node_rpc.SetClusterConfigResponse
	15, // 18: node_rpc.StoreService.GetClusterConfig:output_type -> node_rpc.GetClusterConfigResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_rpc_node_rpc_proto_init() }
func file_internal_rpc_node_rpc_proto_init() {
	if File_internal_rpc_node_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_node_rpc_proto_rawDesc), len(file_internal_rpc_node_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_node_rpc_proto_goTypes,
		DependencyIndexes: file_internal_rpc_node_rpc_proto_depIdxs,
		MessageInfos:      file_internal_rpc_node_rpc_proto_msgTypes,
	}.Build()
	File_internal_rpc_node_rpc_proto = out.File
	file_internal_rpc_node_rpc_proto_goTypes = nil
	file_internal_rpc_node_rpc_proto_depIdxs = nil
}
